---
# tasks file for grafana
- name: add chart to cluster
  git:
    repo: https://github.com/skorik-kirill/helmcharts.git
    dest: /tmp/chart
    update: no
- name: install chart
  command: helm install --name grafana  /tmp/chart/grafana
